### ISSUE TITLE
Consider using the master branch for the latest code instead of develop

### ISSUE THREAD

**Issue by pedrocr** [klauspost/rawspeed#10]
General git practice is that master has the latest code and then there are other branches for stable versions and tags for specific releases. It's not a big issue but it would make it easier sometimes (e.g., github defaults pull requests to happen against master).

**Comment by klauspost** [comment]
I don't know much about GIT, but I found this model, which I find sensible:

http://nvie.com/posts/a-successful-git-branching-model/

I don't want breaking/untested changes in master, so I keep them in "develop" until they are production ready.
