### ISSUE TITLE
Suggestion for a safer getData() API

### ISSUE THREAD

**Issue by pedrocr** [klauspost/rawspeed#137]
Hi klaus,

We've found some out-of-bounds reads in rawspeed that are potential security issues. I've thought of a way to improve FileMap::getData() so that the bounds checks are mandatory:

https://github.com/darktable-org/darktable/pull/1099

Do you agree with going down this path?

Cheers,

Pedro

**Comment by klauspost** [comment]
Yes. Looks very nice, and simplifies a lot of the places it is used.

**Comment by pedrocr** [comment]
Cool, I'll wrap it up, get it merged in darktable, and then do a PR here.
