### ISSUE TITLE
develop branch compiler warning signed/unsigned comparison

### ISSUE THREAD

**Issue by pmjdebruijn** [klauspost/rawspeed#14]
GCC 4.8 seems to be pedantic about signed/unsigned comparisons by default:

RawSpeed/Camera.cpp:186:33: warning: comparison between signed and unsigned 
                     integer expressions [-Wsign-compare] if (strlen(key) != cfa.size.x) {

x/y seems to be defined as int, while strlen is a size_t.

**Comment by klauspost** [comment]
No problem. It should be fixed now.
