### ISSUE TITLE
Canon 80D Support

### ISSUE THREAD

**Issue by dabbill** [klauspost/rawspeed#155]
Here are some sample images from the Canon 80D. 2 RAW straight from the camera and 2 DNG files using Adobe DNG converter 9.5.1. Tried to upload more photos but kept getting an error. Below is a link to public dropbox with more samples. I am running darktable-git release.2.1.0.r1031.gdf4eb00-1 from Arch AUR.

ISO range:
100,125,160,200,250,320,400,500,640,800,1000,1250,1600,2000,2500,3200,4000,5000,6400,8000,10000,12800,16000
"H" (expanded equivalent) 25600

https://www.dropbox.com/sh/17yxb36piaok77c/AADicWPIyZbSjIMT105mYfHma?dl=0

RawSpeed:Unable to find camera in database: Canon Canon EOS 80D 
[rawspeed] Camera 'Canon' 'Canon EOS 80D', mode '' not supported, and not allowed to guess. Sorry.
[temperature] failed to read camera white balance information from `IMG_0003.CR2'!
[colorin]`Canon Canon EOS 80D' color matrix not found!
[colorin] `Canon Canon EOS 80D' color matrix not found!
[colorin]`Canon Canon EOS 80D' color matrix not found!

libgphoto2 has been updated on git to have basic support for the 80D

**Comment by dabbill** [comment]
I have added the basic Canon 80D support in darktable git tree.

**Comment by LebedevRI** [comment]
Was fixed by #157
