### ISSUE TITLE
Nikon, compressed raws: an issue with whitelevel

### ISSUE THREAD

**Issue by LebedevRI** [klauspost/rawspeed#158]
@klauspost 
Hi.

I have noticed a strange thing.

Sample raw file is attached to https://redmine.darktable.org/issues/11135

When converting it to dng, the metadata says Whitelevel=3880.
If i load it via rawspeed, the used whitelevel is 3880.

But if i load the original raw file, rawspeed tells me it's whitelevel is 4095.
(Despite the fact that in cameras.xml i set whitelevel to 3880.)

And the histograms/brightness(?) for these 2 versions of the same image do not match.

Offending lines:
https://github.com/klauspost/rawspeed/blob/00f70efab95856d0421ca37b6c708be8cf55ec54/RawSpeed/NikonDecompressor.cpp#L94-L95

If i manually set whitelevel for that nef to 3880, or delete these 2 lines, the histograms and brightness(?) do match.
(not counting slight differences in crop)

Which one is wrong? The dng metadata or those overrides?

**Comment by LebedevRI** [comment]
I have bad news :(
I have asked D800 owner to take one raw image per mode.
And the images with mode = compressed have pink-ish highlights.
If i manually set the white level to the one in DNG, those highlight are white.

Which means, the DNG metadata is correct and https://github.com/klauspost/rawspeed/blob/00f70efab95856d0421ca37b6c708be8cf55ec54/RawSpeed/NikonDecompressor.cpp#L94-L95 are absolutely wrong and must be exterminated.

**Comment by LebedevRI** [comment]
@klauspost can you please give any comment on this?

**Comment by klauspost** [comment]
Well, isn't this a result of PR #157 - more specifically:

> So i decided that is not ok, and changed NefDecoder to only accept explicit entries with mode="{bitness}bit-{compressed/uncompressed}".
> And that did result in catching some cases.

**Comment by LebedevRI** [comment]
Uhm, no?
The value set in cameras.xml for whitelevel is not used, but overridden by those 2 lines with power-of-two-minus-one

**Comment by LebedevRI** [comment]
Here, the samples i used: https://www.dropbox.com/s/jrgn314cax37j5a/D800-RAW.zip?dl=0

**Comment by LebedevRI** [comment]
@klauspost ok, more specific question
Is there any specific reason why these 2 lines are here?
https://github.com/klauspost/rawspeed/blob/00f70efab95856d0421ca37b6c708be8cf55ec54/RawSpeed/NikonDecompressor.cpp#L94-L95

They result in different white level compared to the DNG converted from that same NEF, and in purple-ish highlights.

**Comment by klauspost** [comment]
AFAIR it was inspired by similar functionality in dcraw.

**Comment by LebedevRI** [comment]
> dcraw.

That would explain it... :(
Thank you, i will fix it in darktable.

**Comment by LebedevRI** [comment]
Ok, fixed in darktable: https://github.com/darktable-org/darktable/commit/6810787e316f3a29af2b32d63529c34efec57e36
Unless i turn out to be really wrong, once most of whitelevels are fixed,, this will eventually be in a PR.
