### ISSUE TITLE
Coding style?

### ISSUE THREAD

**Issue by LebedevRI** [klauspost/rawspeed#167]
For obvious reasons, it would be awesome to know which coding style is preferred.
Ideally, in form of [.clang-format](http://clang.llvm.org/docs/ClangFormatStyleOptions.html)
And it would be super awesome if it's some predefined style (see http://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options, `BasedOnStyle`) - like LLVM, Google, Chromium, Mozilla or WebKit.

**Comment by axxel** [comment]
+1 :-)
