### ISSUE TITLE
Strange if statement in RawDecoder.cpp

### ISSUE THREAD

**Issue by pedrocr** [klauspost/rawspeed#35]
Line 541 of RawDecoder.cpp has this if statement:

``` C
    if (me->taskNo >= 0)
      me->parent->decodeThreaded(me);
    else
      me->parent->decodeThreaded(me);
```

This looks obviously wrong as both branches do the same thing. Is the if statement useless or is one of the branches wrong?

**Comment by pedrocr** [comment]
It would seem the if is useless because it's always true as taskNo is unsigned. clang complains about this.

**Comment by pedrocr** [comment]
Klaus, this isn't fixed, my pull request fixed most coverity but it didn't fix this one or the X3f ones.

**Comment by pedrocr** [comment]
Did you look at the code snippet? Any idea what is going on here?

**Comment by klauspost** [comment]
Code is now removed.
