### ISSUE TITLE
Incorrect decoding of some DNG files

### ISSUE THREAD

**Issue by LibRaw** [klauspost/rawspeed#45]
RawSpeed (master branch, have not tested develop branch) decode some DNG files incorrectly.
I was unable to quickly find the problem, so the bug report here.

Sample file: https://www.dropbox.com/s/t08h2djogfcti06/DR100.dng
It decodes this way: https://www.dropbox.com/s/cjy1987itfeq2ga/Screenshot%202014-08-20%2014.25.51.png
While LibRaw/dcraw do it right: https://www.dropbox.com/s/cie45bwudlr5ksx/Screenshot%202014-08-20%2014.25.26.png

All files I have are from Fuji cameras, converted from RAF to DNG by Adobe DNG Converter 8.x
These files are 'normal bayer', not X-Trans or 'rotated' SuperCCD.

**Comment by LibRaw** [comment]
Followup:  this is because these DNG files use SamplesPerPixels tag equal to 2 (so, each pixel contains values for two sub-images used in Fuji format).
LibRaw/dcraw skips second sub-image, while RawSpeed decodes two values into two pixels.

**Comment by klauspost** [comment]
Fixed in https://github.com/klauspost/rawspeed/commit/8bff993e31b15b4b57fb6dcc32f5ccd039d89b03 

Note, that I do NOT discard values, so if you need the same output, you would need to discard them with a conversion. For these images RawImage->getCpp() will return 2 and RawImage->isCFA will be true.
