### ISSUE TITLE
Error when handling DNG files larger than 256Mb

### ISSUE THREAD

**Issue by LibRaw** [klauspost/rawspeed#50]
In  LJpegPlain::decodeScanLeft3Comps (and, very likely, in other DNG formats too), offsets table is 32-bit:
offset = new uint32[slices+1];
Low 28 bits of offset is offset in data, while upper 4 bits are slice number:
 offset[slice] = ((t_x + offX) \* mRaw->getBpp() + ((offY + t_y) \* mRaw->pitch)) | (t_s << 28);

This effectively disables offsets larger than 256M (2^28)

Unfortunately, such offsets may exists. For example, this file:
https://www.dropbox.com/s/zteexbtcqmmvq4h/r021f07.dng?dl=0
The file is converted from Nikon Scan .NEF (6x6 medium format scan by Nikon Coolscan 9000) file by Adobe DNG converter image size is ~81Mpix (8900x8900), 6 bytes in pixel, so possible offset is ~500M

Even for bayer images (2 bytes per pixel), 28-bit offsets will limit resolution to 128Mpix, while 200-Mpix images are possible today (Hasselblad 200-MS). Situation is worse for linear (demosaiced) DNGs, the limit is about 42Mpix, while single shot cameras are up to 80Mpix today.

Possible solution: change offset[] to 64 bit. Use full 32 lower bits as offset. This will limit image size to 4Gb, so 2Gpix of  bayer images and ~0.7Gpix of linear RGB images.

**Comment by klauspost** [comment]
Nice find. I will probably modify the "generic" function for this, since it will otherwise be a generic slowdown (keeping things in level 1 cache is critical)

**Comment by LibRaw** [comment]
I cannot understand your statement.
maximum slices count is 15 (so, 4 bit), offsets[] table is slices+1 in size;
So, for 32-bit offsets, the table will fit in 64 bytes (16*4), for 64-bit offsets - in 128 bytes.So, 2 or 4 cache lines.
L1 cache is about 500 times larger.

**Comment by LibRaw** [comment]
I've changed offset[] to offset64[] for easy refactoring (so, compiler warns until all places was fixed).
Here is my patch: https://www.dropbox.com/s/i64gott37ekx791/offset64.patch?dl=0
Sorry for do not use github pull mechanics, my repo is not synced with github.

Maximum data offset is now 32bit, this is enough for 2GPix bayer images and for 0.5-0.7Gpix 4/3-component linear dngs. Enough if we want to keep RawSpeed 32-bit compatible.

**Comment by klauspost** [comment]
See PR #52 ... If that works for you, I will merge it.

**Comment by klauspost** [comment]
The reason for not using 64 bits is that 64 bit shifts are very slow on 32 bit platforms.

I don't see any reason to slow down 99% of all decodes, so we handle this situation separately.

It still decodes at ~80MP/sec on my 5 year old Q6600 system.

**Comment by LibRaw** [comment]
Offset calculation is called once per slice. With maximum 16 slices per image, the speed difference is not measureable.

**Comment by LibRaw** [comment]
#52: unable to check right now, I use my own 64-bit offset code. Sometimes in future I'll rebase to current rawspeed from Github. Anyway, I'll wait until development branch will be merged to master.

**Comment by klauspost** [comment]
No, it is used "slices" times per line, see:

uint32 slices = (uint32)slicesW.size() \* (frame.h - skipY);

In all DNG's, that is 1 per line (slices are only a CR2 concept).

**Comment by klauspost** [comment]
I have merged code, that uses the generic decoder, if 28 bits for offsets isn't enough.
