### ISSUE TITLE
Missing Decode16BitRawUnpacked() method

### ISSUE THREAD

**Issue by BAndiT1983** [klauspost/rawspeed#55]
Hi, following error occurs while compiling:

/home/.../RawSpeed/RafDecoder.cpp:98: error: 'Decode16BitRawUnpacked' was not declared in this scope
     Decode16BitRawUnpacked(input, width*2, height);

I haven't found Decode16BitRawUnpacked() anywhere, only Decode12BitRawUnpacked(). Other methods are for big-endian only.

**Comment by pedrocr** [comment]
That's defined here:

https://github.com/klauspost/rawspeed/pull/31/files

This is yet to be merged. I guess I used that function in another pull request and didn't notice it?

**Comment by BAndiT1983** [comment]
Okay, thanks for the info. I'll merge it locally as i'm testing RawSpeed at the moment, because of LibRaw's slow performance.

By the way, such things like FileReader are not really portable, e.g. LPCWSTR and similar Windows-only data types. Should i open another item for it or is it planned in the future?

**Comment by pedrocr** [comment]
> By the way, such things like FileReader are not really portable, e.g. LPCWSTR and similar Windows-only data types. Should i open another item for it or is it planned in the future?

Don't know what that is. I only use rawspeed in Linux with darktable.

**Comment by BAndiT1983** [comment]
I meant the FileReader module in RawSpeed. Nevermind, maybe i will make a pull request when i have time and fix some things.

**Comment by pedrocr** [comment]
I had a look, LPCWSTR is typedef char\* in Common.h on Linux and OSX. I think klaus runs rawspeed on windows with Microsoft tooling and I know it works fine on Linux and OSX as well.

**Comment by pedrocr** [comment]
This should be fixed in current develop branch
