### ISSUE TITLE
Nikon sNEF files are too saturated

### ISSUE THREAD

**Issue by pedrocr** [klauspost/rawspeed#56]
Hi klaus, your new sNEF code looks great. Unapplying the WB is definitely the way to go. Unfortunately it seems all the colors in those files are way too saturated when compared to identically processed normal NEF files. I've tested this with both D810 and D4S files. Any idea what could be happening?

**Comment by klauspost** [comment]
It could be that the chroma is also gamma compressed, just like the luma component.

It would make sense to do a lookup table for the gamma values anyway, which will save a int->float conversion.

**Comment by pedrocr** [comment]
I get a very decent result just by dividing cb and cr by 4.0f. Could this be some kind of problem with your 8x scaling of the numbers?

**Comment by pedrocr** [comment]
@LibRaw can probably shed some light on the correct curves to use. This seems to be the relevant curve in libraw:

https://github.com/LibRaw/LibRaw/blob/master/src/libraw_cxx.cpp#L1092-L1118

**Comment by klauspost** [comment]
ok, seems like they compressed on input R/G/B, which seems a little odd. We should be able to do it better than libraw, which does 3 passes over the image.

**Comment by pedrocr** [comment]
According to @LibRaw that curve was derived experimentally by doing test shots of a step wedge in sNEF and NEF. Don't know how much of that is model specific.

**Comment by LibRaw** [comment]
And sNEF/NEF on the same scene match very well if you're using LibRaw :). The difference is in extreme highlights, where sNEFs do not perform well.

**Comment by pedrocr** [comment]
I've been trying to have another look at this. rawsamples has a series of samples that are useful to understand how this works:

http://rawsamples.ch/raws/nikon/RAW_NIKON_D810.7z

**Comment by klauspost** [comment]
I have changed the code to produce output similar to libraw:

https://github.com/klauspost/rawspeed/commit/3b53d8c2c8507d861063024f133ed8da5d01561c

However, since we deliver the output unbalanced, I don't do any "magic" whitepoint clipping. That should be handled the same way as ordinary clipping, meaning by adjusting the whitepoint.

I am coding "blind", since I don't have Linux running at the moment, so whitepoint is a pure guess, and maybe should be a little lower.

**Comment by LibRaw** [comment]
Nikon sRAWs are already white balanced and converted to sRGB (if you use ours YCC to RGB coeffs).
So, if your calling application knows nothing about Nikon sNEFs (and process these files same way as other Nikon data), you need to
 1) return white balance to unbalanced
 2) return color space from sRGB to Nikon's

**Comment by klauspost** [comment]
I use option 1) - I reverse the whitebalance.

**Comment by LibRaw** [comment]
This is not _options_, but things that need to be done _both_
If not, calling application will receive normal NEF data in Nikon sensor colorspace, sNEF in sRGB space and no way to know what colorspace is real.

**Comment by klauspost** [comment]
So this is _sRGB_, and not camera space. Wow - Nikon really (yet again) takes the crown for the most stupid useless format (again).

So the output from libraw is 16 bit linear sRGB (with camera whitebalance applied)?

**Comment by LibRaw** [comment]
Nikon stores the data in YCC format.
You may convert it to any RGB you want, just change conversion matrix.

**Comment by LibRaw** [comment]
And, yes, LibRaw outputs the data in sRGB. This is not a problem for LibRaw because it outputs color conversion matrix too (camera RGB to sRGB by default). In sNEF case the color matrix is diagonal-ones.

**Comment by pedrocr** [comment]
So to actually fix this we'd need the color matrix in cameras.xml? We discussed that in issue #42.

**Comment by LibRaw** [comment]
RawSpeed _already_ contains some kind of 'color matrix' when doing YCC to RGB transform.

Generally, raw reader API should provide not only raw values itself, but metadata too. You're just starting to extract white balances :), adding color data to the API is good too.

That's why I use RawSpeed only as raw values decoder, keeping metadata extraction on LibRaw's side:

**Comment by pedrocr** [comment]
Just merged the latest code into darktable and this does look much better now. Still more contrast than normal NEF files which I assume is because of the color matrix.

**Comment by pedrocr** [comment]
dcraw has recently added some code to handle this:

https://github.com/pedrocr/dcraw/commit/83cadf5f796ab47c18d990ecbe24e83efbdc6a1a

**Comment by klauspost** [comment]
Cool - I am planning to look through stuff tomorrow, so I will look at this and the pending PRs.

**Comment by klauspost** [comment]
I made an implementation similar to dcraw in #86.  I cannot do visual tests ATM, but it seems to output similar to dcraw.

If you have the time, give it a spin, and feel free to give feedback if it is an improvement.

**Comment by klauspost** [comment]
Closed with PR #86 and #88
