### ISSUE TITLE
Pentax K110D support

### ISSUE THREAD

**Issue by mazhe** [klauspost/rawspeed#59]
Hi, I noticed that older PEF decompressor were added and that the Pentax K100D was now supported by rawspeed.

The Pentax K110D is a K100D without sensor stabilization, so adding support boils down to copy/paste the relevant sections. Would you consider commiting the following patch?
(tested with rawspeed in darktable)

``` diff
diff --git a/data/cameras.xml b/data/cameras.xml
index 1d2f04f..0c80300 100644
--- a/data/cameras.xml
+++ b/data/cameras.xml
@@ -3604,6 +3604,16 @@
                <Crop x="0" y="0" width="3040" height="2024"/>
                <Sensor black="127" white="3950"/>
        </Camera>
+       <Camera make="PENTAX Corporation" model="PENTAX K110D">
+               <CFA width="2" height="2">
+                       <Color x="0" y="0">RED</Color>
+                       <Color x="1" y="0">GREEN</Color>
+                       <Color x="0" y="1">GREEN</Color>
+                       <Color x="1" y="1">BLUE</Color>
+               </CFA>
+               <Crop x="0" y="0" width="3040" height="2024"/>
+               <Sensor black="127" white="3950"/>
+       </Camera>
        <Camera make="PENTAX Corporation" model="PENTAX K100D Super">
                <CFA width="2" height="2">
                        <Color x="0" y="0">RED</Color>
@@ -3624,6 +3634,16 @@
                <Crop x="0" y="0" width="3040" height="2024"/>
                <Sensor black="127" white="3950"/>
        </Camera>
+       <Camera make="PENTAX" model="PENTAX K110D">
+               <CFA width="2" height="2">
+                       <Color x="0" y="0">RED</Color>
+                       <Color x="1" y="0">GREEN</Color>
+                       <Color x="0" y="1">GREEN</Color>
+                       <Color x="1" y="1">BLUE</Color>
+               </CFA>
+               <Crop x="0" y="0" width="3040" height="2024"/>
+               <Sensor black="127" white="3950"/>
+       </Camera>
        <Camera make="PENTAX Corporation" model="PENTAX *ist D">
                <CFA width="2" height="2">
                        <Color x="0" y="0">RED</Color>
```

Thank you very much for your work!

**Comment by pedrocr** [comment]
There may be other slight differences besides that. Could you provide an example file for testing? You can probably attach one here. It would also be nice if you could submit one to rawsamples.ch so there's a public collection available.

**Comment by mazhe** [comment]
I thought they had one: I'll do a good one later (it's night time where I am), in the meantime, here is one: https://www.alkumuna.eu/~mazhe/share/IMGP9877.PEF
As for the differences, for what it is worth, the french website introduce the K110D as the "unstabilized version of the K100D"...

**Comment by pedrocr** [comment]
As I suspected there are slight differences. Here are the correct settings:

``` xml
    <Camera make="PENTAX Corporation" model="PENTAX K110D">
        <CFA width="2" height="2">
            <Color x="0" y="0">RED</Color>
            <Color x="1" y="0">GREEN</Color>
            <Color x="0" y="1">GREEN</Color>
            <Color x="1" y="1">BLUE</Color>
        </CFA>
        <Crop x="0" y="0" width="0" height="0"/>
        <Sensor black="127" white="4095"/>
    </Camera>
```

The black and white points are different in this sensor. Everything else is the same (width and height are just specified differently). Not sure if we also need the version that's just "PENTAX" but I'll add it anyway. I've added support to darktable here:

https://github.com/darktable-org/darktable/commit/ca627577c7897cff28ec68b0dd426429e3d0d19a

And we need to do a rawspeed PR with the cameras.xml changes we've been accumulating.

**Comment by mazhe** [comment]
Thanks, that's great! I've been working on basecurve profile, but I wanted to take care of the rawspeed aspect first :)

**Comment by pedrocr** [comment]
If you're using this in darktable you can just file bug reports there. We add support for the cameras directly and then submit pull requests to rawspeed with the changes.

**Comment by klauspost** [comment]
Thanks! Added in https://github.com/klauspost/rawspeed/commit/3372c61573b6095d37251dbacc4437eda3f60b2d
