### ISSUE TITLE
Nikon 1 S2 has broken colors

### ISSUE THREAD

**Issue by pedrocr** [klauspost/rawspeed#63]
Hi klaus,

I just tried to add support for the Nikon 1 S2 and the colors are broken. Looking at the color histogram it seems the blue and red channels have their blackpoint much higher than the green channel. The DNG conversion looks fine and uses the same WB so it doesn't seem to be that. Any clues? Here's a link to a bunch of test files:

https://www.dropbox.com/sh/nwphevcafm1p8ft/AAB4sORpcUFswycT4hbt6wPka

Cheers,

Pedro

**Comment by klauspost** [comment]
I have added a hint that allows you to override the individual blacklevels. I don't have more time today, so I hope this can bring you further along.

https://github.com/klauspost/rawspeed/commit/606dacbe5c0a86328704a90c9c0b7c632e17d240

(the same order as the in the CFA tag)
A hint could be:
``<Hint name="nikon_rgb_black" value="10,20,30,20"/>`

**Comment by pedrocr** [comment]
I don't know what I was doing wrong before but this was enough after all:

``` xml
  <Camera make="NIKON CORPORATION" model="NIKON 1 S2" decoder_version="4">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="200" white="4095"/>
    <Hints>
      <Hint name="nikon_override_auto_black" value=""/>
    </Hints>
  </Camera>
```

I could swear I had tried that before but apparently not.
