### ISSUE TITLE
Green tint in shadows of Sony NEX RAW images

### ISSUE THREAD

**Issue by bronger** [klauspost/rawspeed#78]
In the shadow areas of the linked image (the houses at the bottom), Darktable shows a greenish colour.  dcraw doesn't exhibit this behaviour.  The Darktable developers told be to report it here.  The URL contains three RAWs:  The problematic RAW with the grennish houses at ISO 100, and two black images at ISO 100 and ISO 1600.

https://bob.ipv.kfa-juelich.de/bronger/nex-7_green/

**Comment by klauspost** [comment]
Should be fixed. Thanks for the report and samples.
