### ISSUE TITLE
Consider changing to Unix line endings uniformly

### ISSUE THREAD

**Issue by pedrocr** [klauspost/rawspeed#9]
The code seems to use a mix of Unix and Windows line endings. This doesn't make much sense and Unix style line endings would generally be preferable. Running dos2unix on all the files should be enough to do the conversion in one go.

**Comment by klauspost** [comment]
Yeah - seems like that was introduced with the svn->git conversion.

**Comment by pedrocr** [comment]
Here's a pull request to fix that:

https://github.com/klauspost/rawspeed/pull/12

**Comment by pedrocr** [comment]
I saw you closed the pull request for this. It was probably outdated and wouldn't merge cleanly. Do you want me to do a new one or do you want to handle that yourself?

**Comment by pedrocr** [comment]
With the last sNEF changes now some files are a mix of DOS and Unix line endings. Running dos2unix on the whole repository would be great.

**Comment by pedrocr** [comment]
klaus, next time you are working on rawspeed doing one single commit with dos2unix would be great.
