### ISSUE TITLE
Support for Canon 5DS/5DSR files

### ISSUE THREAD

**Issue by LibRaw** [klauspost/rawspeed#91]
Hi,

Canon 5DS/DSR files are different from all previous Canon files seen:  LJPEG colors (component) count (equal to 4) contributes not only in image width (as in previous canons), but width/height should be multiplied by 2.

Dcraw patch is trivial (it is ugly b.c. based on camera model name, not on other metadata, but works):

```
--- dcraw.c Wed Feb 25 21:18:18 2015
+++ dcraw.1.473_5DS.c   Wed Mar 25 19:05:33 2015
@@ -934,12 +939,14 @@

 void CLASS lossless_jpeg_load_raw()
 {
-  int jwide, jrow, jcol, val, jidx, i, j, row=0, col=0;
+  int jwide, jhigh, jrow, jcol, val, jidx, i, j, row=0, col=0;
   struct jhead jh;
   ushort *rp;

   if (!ljpeg_start (&jh, 0)) return;
   jwide = jh.wide * jh.clrs;
+   jhigh = jh.high;
+   if (!strncmp(model, "EOS 5DS", 7)) jhigh *= 2;

   for (jrow=0; jrow < jh.high; jrow++) {
     rp = ljpeg_row (jrow, &jh);
@@ -949,13 +956,14 @@
       val = curve[*rp++];
       if (cr2_slice[0]) {
    jidx = jrow*jwide + jcol;
-   i = jidx / (cr2_slice[1]*jh.high);
+   i = jidx / (cr2_slice[1]*jhigh);
    if ((j = i >= cr2_slice[0]))
         i  = cr2_slice[0];
-   jidx -= i * (cr2_slice[1]*jh.high);
+   jidx -= i * (cr2_slice[1]*jhigh);
    row = jidx / cr2_slice[1+j];
    col = jidx % cr2_slice[1+j] + i*cr2_slice[1];
       }
+
       if (raw_width == 3984 && (col -= 2) < 0)
    col += (row--,raw_width);
       if ((unsigned) row < raw_height) RAW(row,col) = val;
@@ -5720,8 +5728,16 @@
        tiff_ifd[ifd].height  = jh.high;
        tiff_ifd[ifd].bps     = jh.bits;
        tiff_ifd[ifd].samples = jh.clrs;
-       if (!(jh.sraw || (jh.clrs & 1)))
+       if (!(jh.sraw || (jh.clrs & 1))) {
          tiff_ifd[ifd].width *= jh.clrs;
+               
+       if (!strncmp(model, "Canon EOS 5DS", 13))
+       {
+           tiff_ifd[ifd].width  = jh.wide * 2;
+           tiff_ifd[ifd].height = jh.high * 2;
+       }
+      }
+           
        i = order;
        parse_tiff (tiff_ifd[ifd].offset + 12);
        order = i;
```

I'm not familiar enough with RawSpeed to implement this patch into it myself, hope your help.

Raw samples are available at Imaging Resource: http://www.imaging-resource.com/PRODS/canon-5ds-r/canon-5ds-rA7.HTM

**Comment by klauspost** [comment]
Thanks for the notification!

**Comment by LibRaw** [comment]
Followup: Imaging resources removes samples by Canon's request.

Contact me if you have not downloaded these files yet, I've mirrored all IR samples.

**Comment by klauspost** [comment]
@LibRaw - Sure, if you could upload a few samples here I could take a look at it shortly:

https://www.sendthisfile.com/f.jsp?id=Pm0SfqwTVaSfhj9xXrpYeqfs

**Comment by LibRaw** [comment]
Sendthisfile allows me to select only one file. Send it.

This file and 3 other also uploaded here:
https://www.dropbox.com/sh/xr4javfvdgayuuh/AADAeJTvvLN7S-9214aXCPMNa?dl=0

**Comment by klauspost** [comment]
Added in https://github.com/klauspost/rawspeed/commit/9d17362ab95f1f778ef705b319769fc3623080ac

Thanks for the help!

**Comment by LibRaw** [comment]
Hmm...

```
 if (sof.cps == 4) {
 doubleHeight = true;
 }
```

Most likely, this will fail on Canon 5D Mark II files, where cps is also 4, but not doubleHeight.
Could you please check?

That's why I checked against make/model in my dcraw patch, not against cps (tried, but failed on 5DMk2 files).

May be, additional decoder hint in XML data is needed.

**Comment by klauspost** [comment]
Ah - thanks for notifying.

I added a width/height check, which works on all my current test images, and added a hint to override it, if the check isn't enough in the future.

https://github.com/klauspost/rawspeed/commit/647c46003f41741f2983674cc05d4fc87f576a2d

**Comment by LibRaw** [comment]
And minor optimization to prevent extra data alloc:

```
diff --git a/RawSpeed/Cr2Decoder.cpp b/RawSpeed/Cr2Decoder.cpp
index 1b559b2..a3a6d6c 100644
--- a/RawSpeed/Cr2Decoder.cpp
+++ b/RawSpeed/Cr2Decoder.cpp
@@ -105,6 +105,7 @@ RawImage Cr2Decoder::decodeRawInternal() {
     }
   }

+  if(!doubleHeight) // for double height we'll allocate it later
    mRaw->createData();

   vector<int> s_width;
diff --git a/RawSpeed/LJpegPlain.cpp b/RawSpeed/LJpegPlain.cpp
index fa1f95d..45c922e 100644
--- a/RawSpeed/LJpegPlain.cpp
+++ b/RawSpeed/LJpegPlain.cpp
@@ -738,7 +738,6 @@ void LJpegPlain::decodeScanLeft3Comps() {
 #define COMPS 4

 void LJpegPlain::decodeScanLeft4Comps() {
-  uchar8 *draw = mRaw->getData();
   // First line
   HuffmanTable *dctbl1 = &huff[frame.compInfo[0].dcTblNo];
   HuffmanTable *dctbl2 = &huff[frame.compInfo[1].dcTblNo];
@@ -748,9 +747,12 @@ void LJpegPlain::decodeScanLeft4Comps() {
   if (mCanonDoubleHeight) {
     frame.h *= 2;
     mRaw->dim = iPoint2D(frame.w * 2, frame.h);
-    mRaw->destroyData();
+    //mRaw->destroyData(); => not allocated at CR2decoder for doubleHeight
     mRaw->createData();
   }
+
+  uchar8 *draw = mRaw->getData();
+
   //Prepare slices (for CR2)
   uint32 slices = (uint32)slicesW.size() * (frame.h - skipY);
   offset64 = new uint64[slices+1];
```

line offset may differ because I still use old RawSpeed copy (master branch)
