### ISSUE TITLE
Add a canonical name to cameras

### ISSUE THREAD

**Issue by pedrocr** [klauspost/rawspeed#95]
To make it easier to reference cameras in lists of color matrices, WB presets, etc it would be nice to have a single canonical name reported by rawspeed. Here's my suggestion on how to do it:
- Start reporting canonical_name and canonical_model instead of just make and model. Default those two values to whatever is in the <Camera> definition. For cameras without aliases the values will be the same, for cameras with aliases it will be a consistent name
- Create a new tag of the form <Canonical make="SomeMake" model="SomeModel"> so that the sometimes ugly and repetitive names can be replaced with something sensible. This avoids reporting the Nikon D800 as make "NIKON CORPORATION" model "NIKON D800" and instead do "Nikon" and "D800"

If this sounds ok I'll go ahead and prepare a PR.

**Comment by klauspost** [comment]
Yes, could you match it up with the "Unique Camera Id" Adobe uses in their DNG files. Here is a list with camera make/model -> camera id

https://github.com/rawstudio/rawstudio/blob/master/profiles/rawstudio-cameras.xml

If you have newer files, just convert them to DNG and look at the metadata.

**Comment by pedrocr** [comment]
Using the Adobe naming sounds like a great idea. I'd prefer having make and model separate though for other uses. It's not as simple as splitting on the first space as in the Konica Minolta case.

**Comment by klauspost** [comment]
Yeah, I can see what you mean. How about:

``` xml
    <Camera make="Canon" model="Canon EOS 100D">
        <ID make="Canon">Canon EOS 100D</ID>
    </Camera>
```

Would that suit your needs?

The 'other' way, I don't like, since it relies on the assumption that `UniqueID = make+" "+model`, which is hidden. However, if you really want I can live with it.

``` xml
    <Camera make="Canon" model="Canon EOS 100D">
        <ID make="Canon" model="EOS 100D"/>
    </Camera>
```

**Comment by pedrocr** [comment]
I think the second looks better. The first also requires an assumption to get the model out. Something like the model is the ID minus the make and a space. That sounds a little sketchy. make+" "+model seems quite reasonable to me but we could even go the fully redundant path:

``` xml
    <Camera make="Canon" model="Canon EOS 100D">
        <ID make="Canon" model="EOS 100D">Canon EOS 100D</ID>
    </Camera>
```

Doesn't seem needed though and could lead to errors.

**Comment by klauspost** [comment]
Ok, let's keep the simple one. 

I created a list with all current "UniqueCameraModel" values.

https://gist.github.com/klauspost/8007317704f2fb1c2cd6

There are a few case differences (`Leica` vs `LEICA`, same for Pentax & Ricoh). The DNG spec doesn't specify if they are case sensitive, so I have kept the case of the value in the DNG files:

> UniqueCameraModel defines a unique, non-localized name for the camera model that created
> the image in the raw file. This name should include the manufacturer's name to avoid conflicts,
> and should not be localized, even if the camera name itself is localized for different markets
> (see LocalizedCameraModel).
> This string may be used by reader software to index into per-model preferences and
> replacement profiles

Does this make things easier?

**Comment by klauspost** [comment]
Note that Leica in their wisdom have given their cameras the unique id "GR" "S2", and "M8 Digital Camera". However, they only write DNG, so they don't have camera definitions.

**Comment by pedrocr** [comment]
I'd prefer to always have the same case so when these values are used in user-visible places there is some consistency. For example in darktable we generate tags with the camera manufacturers and it would be nice not to have both "LEICA" and "Leica" in the tag list.

**Comment by klauspost** [comment]
ok, then we'll have to go with the full "redundant" option.

``` xml
<ID make="Canon" model="EOS 100D">Canon EOS 100D</ID>
```

I will update the gist.

**Comment by pedrocr** [comment]
Well it would have to be:

``` xml
<ID make="Samsung" model="GX20">SAMSUNG GX20</ID>
```

If the difference is only the case we could potentially leave it as before and just do the "Camel Casing" in code after. So go from this:

``` xml
<ID make="SAMSUNG" model="GX2"/>
```

to

``` cpp
canonical_make = "Samsung"
canonical_model = "GX2"
canonical_id = "SAMSUNG GX2"
```

How does that sound?

**Comment by pedrocr** [comment]
After thinking about this some more I think our best bet is to support both formats. So:

``` xml
<ID make="Samsung" model="GX2">SAMSUNG GX2</ID>
<ID make="Sony" model="SLT-A57"/>
<ID make="Leica" model="M8">M8 Digital Camera</ID>
```

How does that sound? That way there's no magic in the code and anything can be set.

**Comment by klauspost** [comment]
Yeah. Let's go for that. I can do the code in a couple of days. If you would take the task of adding it to the xml that would be awesome.

**Comment by pedrocr** [comment]
I have working code and cameras.xml here:

https://github.com/darktable-org/darktable/pull/899

We're still going over the best way to integrate it but the rawspeed part is probably good already.

**Comment by klauspost** [comment]
Looks good.

**Comment by klauspost** [comment]
I will close this now.
